widget_driver/pubspec.yaml
widget_driver_annotation/pubspec.yaml
widget_driver_generator/pubspec.yaml
widget_driver_test/pubspec.yaml

According to this guide on publishing dart packages, it is good to add a link to the repos in the pubspec yaml: https://docs.flutter.dev/development/packages-and-plugins/developing-packages#publish
Fixes this issue: #41

Adds link to repositories to the pubspec files

---

widget_driver/test/widget_driver_test.dart
widget_driver_test/CHANGELOG.md
widget_driver_test/lib/src/utils/test_drivable_widget.dart
widget_driver_test/lib/src/utils/test_runtime_environment_info.dart
widget_driver_test/lib/src/utils/test_widget_driver_provider.dart
widget_driver_test/lib/src/widget_tester_extension.dart
widget_driver_test/pubspec.yaml

There was a bug in the widget_driver_tests for the driverTest helper.
It didn't create the testable drivers correctly. So they were not really disposed when the widget went off the widget tree.
This change fixes this so that driver are loaded and disposed correctly by the test helper.
This is the second part needed to fix the remaining unit test in widget_driver.
After this PR has been merged, then I will deploy a new version of the `widget_driver_test`
and then in the upcoming later final PR I will tell `wdiget_driver` to use this new version of `widget_driver_test` and add the remaining unit tests.

Fixes driverTesterHelper so that widgets are loaded correctly and diposed correctly

---

scripts/run-tests.sh
widget_driver_annotation/CHANGELOG.md
widget_driver_annotation/example/README.md
widget_driver_annotation/lib/src/driver_annotations.dart
widget_driver_annotation/pubspec.yaml
widget_driver_annotation/test/dummy_test.dart
widget_driver_annotation/test/generate_test_driver_test.dart
widget_driver_annotation/test/test_driver_default_future_value_test.dart
widget_driver_annotation/test/test_driver_default_value_test.dart
widget_driver_annotation/test/test_helpers/annotation_info_getter.dart

Adds a new annotations for handling `Future` return values.
And also refactors existing annotations and renames them to more descriptive names.
This is an API breaking change!
Solves issue #74 
**Background**
When your driver has a method which returns a future. Then you currently run into problem.
Since if you want to provide a default value using @DriverAction then the value which you pass in there, it needs to be a const value. Since the annotation needs to have a const constructor.
And you cannot out-of-the-box create a const-future.
**Solution**
We add a new annotation which you can use when your function is returning a future.
The new annotation is called: `TestDriverDefaultFutureValue` and into it you pass the return value of the future which you are returning. See this example for …

Adds new annotation to provide return values to future returning methods

---

widget_driver/example/pubspec.yaml
widget_driver/pubspec.yaml
widget_driver_test/CHANGELOG.md
widget_driver_test/pubspec.yaml

I had some issues when I tried to integrate widget_driver_tests into the bmw internal flutter app.
We had a hard coded dependency to mockito in other packages which was lower than the one which was specified in `widget_driver_test`. So I just lowered it here.. We have no real reason to have it higher.. We just mockito to create a help-mock-interface.. So no real business logic.

Lowers the min version for mockito

---

widget_driver/CHANGELOG.md

I forgot to update the Changelog last time I updated the widget_driver.
This PR adds the missing changelog entry

Adds missing Changelog entry for widget_driver for v 0.0.4

---

widget_driver_test/lib/src/utils/test_drivable_widget.dart
widget_driver_test/lib/src/widget_tester_extension.dart

There was a bug with our testing framework that did not allow for a creation of multiple TestDrivableWidgets in one test. The reason was that the flutter element tree did not recognize the new widget as new and therefore reused the old one. This gives the TestDrivableWidget a unique key, thus always forcing the element tree to use the new widget.

Fix bug where a new TestDrivableWidget is ignored by element tree if one was already created

---

widget_driver/README.md
widget_driver/lib/src/dependency_provider.dart
widget_driver/lib/src/utils/empty_default.dart
widget_driver/lib/src/utils/test_driver_empty_default_implementation.dart
widget_driver/lib/widget_driver.dart
widget_driver/test/dependency_provider_test.dart

This PR adds a helper class which you can use if you need to inject a dependency into the BuildContext from a normal non-drivable widget.
**Why is this needed?**
If you try to create/resolve a dependency in a build method of a normal widget, that means that any parent widget will also create that dependency when that parent widget is tested..
So then that parent widget needs to provide mock data for all dependencies which that dependency needs..
The fix for this would be to use a driver.. and the create the dependency in the driver..
But if you have a small widget which has no view logic, it only provides dependnecies, then it is quite a overhead to create a driver for this..
**Solution**
We now offer a `DependencyProvider` which you can use in your normal widgets to create/resolve …

Adds placeholder code for a helper method to get dependencies with fallback support

---

widget_driver/CHANGELOG.md
widget_driver/lib/src/drivable_widget.dart
widget_driver/lib/src/widget_driver.dart
widget_driver/test/widget_driver_test.dart

Adds a didInitDriver optional override method to Drivers.
You can implement it if you need to do some one-time setup work in your driver.
That method is called one time per driver lifecycle.
It is called directly after the `didUpdateBuildContext` has been called for the first time.

Adds didInitDriver method to driver

---

widget_driver/example/lib/resolver/resolver.dart
widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_dependency_injector.dart
widget_driver/example/lib/widgets/home_page/home_page_driver.dart
widget_driver/example/lib/widgets/my_app_driver.dart
widget_driver/example/pubspec.yaml
widget_driver/example/test/driver_tests/coffee_consumption/coffee_counter/coffee_counter_header_section_driver_test.dart
widget_driver_test/CHANGELOG.md
widget_driver_test/README.md
widget_driver_test/lib/src/updatable_dependency.dart
widget_driver_test/lib/widget_driver_test.dart
widget_driver_test/pubspec.yaml

Adds a new helper widget you can use in your driver tests to test the `didUpdateBuildContext` of your drivers.
Solves issue #126

Adds UpdatableDependency test helper widget to widget_driver_test

---

README.md
widget_driver/README.md
widget_driver_annotation/CHANGELOG.md
widget_driver_annotation/README.md
widget_driver_annotation/pubspec.yaml
widget_driver_generator/CHANGELOG.md
widget_driver_generator/README.md
widget_driver_generator/pubspec.yaml
widget_driver_test/CHANGELOG.md
widget_driver_test/README.md
widget_driver_test/pubspec.yaml

In the last commit we only added the WidgetDriver logo to the widget_driver package. 
But not to all the other packages. This commit fixes that and applies to logo to all READMEs.

Add WidgetDriver logo to all READMEs

---

.github/workflows/check-code-quality.yml
scripts/run-example-run-build-runner.sh
scripts/run-tests.sh
widget_driver_annotation/CHANGELOG.md
widget_driver_annotation/pubspec.yaml

We only supported dart sdk versions up to, but not including, 3.0.0.
So any project using flutter 3.10 or later would have issues.
This PR just changes so that the newer version of this package support all version from 3.0.0 up until <4.0.0

Adds support for dart sdk 3.0.0

---

widget_driver_annotation/pubspec.yaml

Seems the `^` format is not allowed when specifying the min sdk.
I got this warning when trying to publish the package:
```
Package validation found the following error:
* ^ version constraints aren't allowed for SDK constraints since older versions of pub don't support them.
Expand it manually instead:
environment:
sdk: ">=3.0.0 <4.0.0"
```
So I changed it and I hope this works.
Running the `dart publish --dry-run` does not really help. Since it also didn't complain before.
So I am not 100% sure this will fix it.. But lets see 😄 🤞

Updates the format of min sdk definition

---

widget_driver/CHANGELOG.md
widget_driver/README.md
widget_driver/doc/code_generation.md
widget_driver/example/example.md
widget_driver/pubspec.yaml
widget_driver_generator/CHANGELOG.md
widget_driver_generator/README.md
widget_driver_generator/example/README.md
widget_driver_generator/pubspec.yaml

We only supported dart sdk versions up to, but not including, 3.0.0.
So any project using flutter 3.10 or later would have issues.
This PR just changes so that the newer version of this package support all version from 3.0.0 up until <4.0.0
This change is now for the widget_driver and the widget_driver_generator.

Adds support for dart sdk 3.0.0 to widget_driver and widget_driver_generator

---

widget_driver/example/README.md
widget_driver/example/lib/pub_dev_example_code/my_first_drivable_widget_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/coffee_community_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_library_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/not_logged_in/register_account/register_account_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_header_section_driver.g.dart
widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.g.dart
widget_driver/example/lib/widgets/coffee_consumption/random_coffee_image_widget/random_coffee_image_widget_driver.g.dart
widget_driver/example/lib/widgets/home_page/home_page_driver.g.dart
widget_driver/example/lib/widgets/home_page/log_in_out_button/log_in_out_button_driver.g.dart
widget_driver/example/lib/widgets/my_app_driver.g.dart
widget_driver/example/pubspec.yaml
widget_driver_test/CHANGELOG.md
widget_driver_test/pubspec.yaml

We only supported dart sdk versions up to, but not including, 3.0.0.
So any project using flutter 3.10 or later would have issues.
This PR just changes so that the newer version of this package support all version from 3.0.0 up until <4.0.0
This updates the widget_driver_tests and the example app

Adds support for dart sdk 3.0.0 to widget_driver_test and example app

---

widget_driver/CHANGELOG.md
widget_driver/doc/testing.md
widget_driver/lib/src/drivable_widget.dart
widget_driver/lib/src/widget_driver_test_config.dart
widget_driver/lib/widget_driver.dart
widget_driver/pubspec.yaml
widget_driver/test/drivable_widget_test.dart
widget_driver/test/test_helpers/build_context_provider.dart
widget_driver/test/widget_driver_test_config_test.dart

There might be times when you actually want to use the real drivers when testing your DrivableWidgets.
This PR adds a `WidgetDriverTestConfigProvider` which you can use to control the config used during testing.
More specifically it gives you the option to control if you:
- always want to use the real drivers for a given test.
- use real drives for a specified list of drivers for a given test.
This PR solves Issue #152

Add testConfigProvider to control use of test drivers

---

widget_driver/example/lib/pub_dev_example_code/my_first_drivable_widget_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/coffee_community_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_library_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_community/not_logged_in/register_account/register_account_page_driver.g.dart
widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_header_section_driver.g.dart
widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.g.dart
widget_driver/example/lib/widgets/coffee_consumption/random_coffee_image_widget/random_coffee_image_widget_driver.g.dart
widget_driver/example/lib/widgets/home_page/home_page_driver.g.dart
widget_driver/example/lib/widgets/home_page/log_in_out_button/log_in_out_button_driver.g.dart
widget_driver/example/lib/widgets/my_app_driver.g.dart
widget_driver/example/lib/widgets/playground/playground_page.dart
widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_child_widget.dart
widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_child_widget_driver.dart
widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_child_widget_driver.g.dart
widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_widget.dart
widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_widget_driver.dart
widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_widget_driver.g.dart
widget_driver/example/pubspec.yaml
widget_driver/example/test/widget_tests/playground/playground_test_widget/playground_test_widget_test.dart
widget_driver_test/CHANGELOG.md
widget_driver_test/README.md
widget_driver_test/pubspec.yaml

The WidgetDriver framework has a new `WidgetDriverTestConfigProvider` from version 1.0.8.
You can use this to configure how TestDrivers are used in testing.
This PR updates the example app to show case how to use these in testing.
And it also updates the README in the widget_driver_test package to contain info about this new `WidgetDriverTestConfigProvider`.
This PR completes the fix for Issue: #152

Updates example app and widget_driver_test with latest info about TestConfigProvider

---

widget_driver/example/build.yaml
widget_driver_generator/CHANGELOG.md
widget_driver_generator/lib/builder.dart
widget_driver_generator/pubspec.yaml

This introduces the option to add "lineLength" to the build.yaml. This will generate the widgetDriver code with the desired line length. It will however not affect the code of other build_runner plugins.
Note that the dart team considers the feature we use as "unoffical" and used for testing. See [this](https://github.com/dart-lang/source_gen/issues/424) as a reference.

introduce lineLength option for generator

---

widget_driver_generator/CHANGELOG.md
widget_driver_generator/lib/src/code_providers/test_driver_code_provider.dart
widget_driver_generator/pubspec.yaml

This fixes https://github.com/bmw-tech/widget_driver/issues/166
```
final MyClass? class = MyClass();
```
until now produced:
```
@override
final MyClass? class = null;
```
This produces:
```
@override
final MyClass? class;
```

[166] Generated optional fields have unnecessary null initialization

---

.github/workflows/check-code-quality.yml
.github/workflows/publish_all_packages.yml

Instead of just using the tag to reference which GitHub action to use, we are pinning it to a specific commit hash for that version. Makes it a bit safer. Also updating the actions to use the latest available version

Refactor GitHub Actions workflows for consistency and clarity, and use fixed versions based on commit hash

---

.github/workflows/create-git-tags-for-publishing.yml

Missed the part that github action has to first checkout the code

Update create-git-tags-for-publishing.yml to checkout the code first

---

.github/workflows/check-code-quality.yml
.github/workflows/create-git-tags-for-publishing.yml
.github/workflows/publish-package.yml
README.md

Readme is updated with description on how to perform publishing to pub.dev

[NO-TICKET]: Updating README.md and GitHub actions
