bmw-tech/widget_driver

.github/test.yaml, widget_driver_annotation/test/dummy_test.dart
Adds a dummy test and a githubAction yaml file to run it
=> Github action to run a dummy test

.github/PULL_REQUEST_TEMPLATE.md
To make it easier to fill in a good description to your PRs and to make them all have a similar layout, 
it makes sense to have a PR template defined.
=> Adds PR template. To make it easier to create PR description and make them more unified

CONTRIBUTING.md, README.md
Adds a dedicated markdown documentation file with information about how to contribute.
And updated the main README with a link into the new contributing.md
=> Adds contributing.md with info about how to contribute to the WidgetDriver

scripts/run-publish.sh
The -f flag is needed to bypass the confirmation in the github action to publish to pub dev
=> force publish to pubdev in githubAction

widget_driver_generator/pubspec.yaml, widget_driver_test/pubspec.yaml
the publishing of generator and test failed. This fixes their dependencies
=> fix pubspec dependencies for generator and test

widget_driver_generator/example/README.md, widget_driver_generator/lib/builder.dart, widget_driver_generator/lib/src/model_visitor.dart, widget_driver_generator/lib/src/widget_driver_generator.dart, widget_driver_generator/pubspec.yaml
- Updated widget_driver_generator/pubspec.yaml with description and platforms
- Fixed formatting
- Added example.md with simple description
- Added some basic documentation to widget_driver_generator classes
=> Update widget driver generator docs

widget_driver_annotation/example/README.md, widget_driver_annotation/pubspec.yaml
Updated description in pubspec and provided simple example.
=> Updated widget_driver_annotation docs

widget_driver_generator/CHANGELOG.md, widget_driver_test/CHANGELOG.md
Added missing changelog updates after minor changes to improve pub.dev scores.
=> Added missing changelog updates

widget_driver/example/ios/Runner.xcodeproj/project.pbxproj, widget_driver/example/lib/widgets/coffee_community/coffee_community_page_driver.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_library_page_driver.dart, widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_page_driver.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.dart, widget_driver/example/lib/widgets/coffee_consumption/random_coffee_image_widget/random_coffee_image_widget_driver.dart, widget_driver/example/lib/widgets/home_page/home_page_driver.dart, widget_driver/example/lib/widgets/home_page/log_in_out_button/log_in_out_button_driver.dart, widget_driver/example/lib/widgets/my_app_driver.dart, widget_driver/pubspec.yaml, widget_driver_generator/CHANGELOG.md, widget_driver_generator/README.md, widget_driver_generator/example/README.md, widget_driver_generator/lib/src/model_visitor.dart, widget_driver_generator/lib/src/utils/code_writer.dart, widget_driver_generator/lib/src/utils/element_utils.dart, widget_driver_generator/lib/src/utils/source_code_generator.dart, widget_driver_generator/lib/src/utils/type_utils.dart, widget_driver_generator/lib/src/widget_driver_generator.dart, widget_driver_generator/pubspec.yaml, widget_driver_generator/test/utils/code_writer_test.dart, widget_driver_generator/test/utils/source_code_generator_test.dart, widget_driver_generator/test/utils/type_utils_test.dart
Solves issue https://github.com/bmw-tech/widget_driver/issues/74
This change updates generator to use new versions of widget_driver_annotation.
This new version of the annotations replaces old annotations with new names.
Now the generator knows how to parse these new annotations correctly.
This PR also:
- Adds unit tests
- Refactors generator code to be more testable and decoupled
- Updates README and exmaple/README to reflect new changes
=> Updates generator to work with new annotations. And refactors generator for more decoupling

Makefile, README.md, scripts/run-example-run-build-runner.sh
This adds the generator make script requested in https://github.com/bmw-tech/widget_driver/issues/72
=> add example_run_build_runner script to makefile

widget_driver/README.md
* Small documentation update, informing about adding the dependency as a first step
=> Update Readme: Usage first step is the dependency

widget_driver_annotation/CHANGELOG.md, widget_driver_annotation/example/README.md, widget_driver_annotation/lib/src/driver_annotations.dart, widget_driver_annotation/pubspec.yaml
I added a new annotation, so that with this PR (#96) we are able to pass data from the driver to the widget.
To enable our pipeline etc. we first have to create a new version of the annotations, which this PR should accomplish, to then bump the version of the generator.
=> Added annotation driverProvidableProperty

widget_driver/example/lib/widgets/coffee_community/coffee_community_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_library_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.g.dart, widget_driver/example/lib/widgets/coffee_consumption/random_coffee_image_widget/random_coffee_image_widget_driver.g.dart, widget_driver/example/lib/widgets/home_page/home_page_driver.g.dart, widget_driver/example/lib/widgets/home_page/log_in_out_button/log_in_out_button_driver.g.dart, widget_driver/example/lib/widgets/my_app_driver.g.dart, widget_driver_generator/CHANGELOG.md, widget_driver_generator/lib/src/widget_driver_generator.dart, widget_driver_generator/pubspec.yaml, widget_driver_generator/test/builder_test.dart, widget_driver_generator/test/widget_driver_generator_test.dart
This changes adds a line which removes code coverage checks from the generated driver files.
Fixes issue #100
=> Issue 100: Adds code-coverage-ignore to generated files

widget_driver/example/lib/widgets/home_page/tabs/home_page_tabs.dart, widget_driver/example/lib/widgets/home_page/tabs/home_page_tabs_builder.dart, widget_driver/example/lib/widgets/playground/playground_page.dart
Adds an empty tab where you can quickly add code to test out driver stuff.
=> Adds a new tab for playground code. Where you can quickly add some test code

widget_driver/README.md, widget_driver/lib/src/utils/test_driver_empty_default_implementation.dart, widget_driver/lib/widget_driver.dart
So far it was hard to provide test driver values for public fields that return complex services that require a lot of overrides. I created a new class called TestDriverEmptyDefaultImplementation that helps here.
=> Add TestDriverEmptyDefaultImplementation to ease testDriverValue creation

widget_driver_generator/CHANGELOG.md, widget_driver_generator/lib/src/code_providers/driver_provider_code_provider.dart, widget_driver_generator/lib/src/code_providers/provided_properties_mixin_code_provider.dart, widget_driver_generator/lib/src/models/providable_field.dart, widget_driver_generator/lib/src/utils/class_utils.dart, widget_driver_generator/lib/src/utils/string_extensions.dart, widget_driver_generator/lib/src/widget_driver_generator.dart, widget_driver_generator/pubspec.yaml, widget_driver_generator/test/code_providers/driver_provider_code_provider_test.dart, widget_driver_generator/test/code_providers/provided_properties_mixin_code_provider_test.dart, widget_driver_generator/test/code_providers/test_driver_code_provider_test.dart, widget_driver_generator/test/utils/class_utils_test.dart, widget_driver_generator/test/utils/string_extensions_test.dart
This makes the change required for #106 and prepares a release of `widget_driver_generator`.
=> Generator changes for state change issues

widget_driver/example/lib/widgets/coffee_community/coffee_community_page_driver.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_page_driver.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.dart, widget_driver/example/lib/widgets/coffee_consumption/random_coffee_image_widget/random_coffee_image_widget_driver.dart, widget_driver/example/lib/widgets/home_page/home_page_driver.dart, widget_driver/example/lib/widgets/home_page/log_in_out_button/log_in_out_button_driver.dart, widget_driver/example/lib/widgets/my_app_driver.dart, widget_driver/example/pubspec.yaml, widget_driver_test/pubspec.yaml
Versions bumps to widget_driver 0.0.6.
Changes to the example app using the new features in 0.0.6.
=> example changes and widgetDriver version bump

widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_header_section.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_header_section_driver.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_header_section_driver.g.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.g.dart
Updates the example app with some code that demonstrates how the new updateBuildContext method of a driver can get called when the driver has a dependency to an inherited widget which changes.
=> Updates example app with an updateBuildContext-dependency

widget_driver/CHANGELOG.md, widget_driver/README.md, widget_driver/example/pubspec.yaml, widget_driver/pubspec.yaml, widget_driver_generator/CHANGELOG.md, widget_driver_generator/pubspec.yaml
Updates the widget_driver and widget_driver_generator to official 1.0.0 versions
And fixes the broken image on the widget_driver readme
=> Updates widget_driver and generator to 1.0.0

widget_driver/example/pubspec.yaml, widget_driver_test/CHANGELOG.md, widget_driver_test/pubspec.yaml
Updates the widget_driver_test to official release 1.0.0
=> Updates widget_driver_test to 1.0.0

widget_driver/CHANGELOG.md, widget_driver/example/example.md, widget_driver/example/lib/pub_dev_example_code/my_first_drivable_widget.dart, widget_driver/pubspec.yaml
We forgot to mention 2 properties in the driver in the example.md readme.
This PR adds them.
=> Fixes small issues with driver in example.md

README.md, widget_driver/README.md, widget_driver_annotation/README.md, widget_driver_generator/README.md, widget_driver_test/README.md
Updates html tag so that they are github compatible
=> Fix readme html formatting issue

widget_driver_annotation/CHANGELOG.md, widget_driver_annotation/pubspec.yaml, widget_driver_generator/CHANGELOG.md, widget_driver_generator/pubspec.yaml, widget_driver_test/CHANGELOG.md, widget_driver_test/pubspec.yaml
Updates version and changelogs
=> Updates version and changelogs

widget_driver/doc/code_generation.md, widget_driver/doc/widget_drivers.md, widget_driver/example/build.yaml, widget_driver/example/lib/pub_dev_example_code/my_first_drivable_widget_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/coffee_community_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_detail/coffee_detail_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_library_page_driver.dart, widget_driver/example/lib/widgets/coffee_community/coffee_library/coffee_library_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/not_logged_in/not_logged_in_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_community/not_logged_in/register_account/register_account_page_driver.g.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_header_section_driver.g.dart, widget_driver/example/lib/widgets/coffee_consumption/coffee_counter/coffee_counter_widget_driver.g.dart, widget_driver/example/lib/widgets/coffee_consumption/random_coffee_image_widget/random_coffee_image_widget_driver.g.dart, widget_driver/example/lib/widgets/home_page/home_page_driver.g.dart, widget_driver/example/lib/widgets/home_page/log_in_out_button/log_in_out_button_driver.g.dart, widget_driver/example/lib/widgets/my_app_driver.g.dart, widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_child_widget_driver.g.dart, widget_driver/example/lib/widgets/playground/playground_test_widget/playground_test_widget_driver.g.dart, widget_driver_generator/CHANGELOG.md, widget_driver_generator/README.md, widget_driver_generator/lib/builder.dart, widget_driver_generator/lib/src/utils/default_return_value_helper.dart, widget_driver_generator/lib/src/widget_driver_generator.dart, widget_driver_generator/pubspec.yaml, widget_driver_generator/test/widget_driver_generator_test.dart
This allows the user to specify defaultTestValues globally inside the build.yaml (standard for build_runner)
=> Add option to specify custom permanent default test values

widget_driver/CHANGELOG.md, widget_driver/example/pubspec.yaml, widget_driver/pubspec.yaml
bumps the example app and changelog for generator 1.2.0
=> bump the example app and changelog for generator 1.2.0

widget_driver_generator/CHANGELOG.md, widget_driver_generator/lib/src/widget_driver_generator.dart, widget_driver_generator/pubspec.yaml
There is a bug in the generator 1.2.0 when no build.yaml is provided. This fixes the bug
=> Fix bug when no build.yaml is provided.

widget_driver_generator/CHANGELOG.md, widget_driver_generator/lib/src/code_providers/test_driver_code_provider.dart, widget_driver_generator/pubspec.yaml, widget_driver_generator/test/code_providers/test_driver_code_provider_test.dart
This is the implementation of https://github.com/bmw-tech/widget_driver/issues/163
=> [163] setters have unnecessary void type

widget_driver_generator/CHANGELOG.md, widget_driver_generator/lib/src/model_visitor.dart, widget_driver_generator/pubspec.yaml
fixes https://github.com/bmw-tech/widget_driver/issues/162, has to wait for https://github.com/bmw-tech/widget_driver/pull/164 to be merged
=> [162] generator generates code for static fields

widget_driver/README.md
Fixed a typo in widget_driver README
=> Fix typo in widget_driver README.md

widget_driver_test/test/driver_tester_test.dart, widget_driver_test/test/mock_driver_test.dart, widget_driver_test/test/updatable_dependency_test.dart, widget_driver_test/test/utils/test_widget_driver_provider_test.dart, widget_driver_test/test/widget_tester_extension_test.dart
Create unit tests for the widget_driver_test package, improving code coverage.
close #111
=> Create widget_driver_test tests

widget_driver/example/android/build.gradle, widget_driver/example/pubspec.yaml, widget_driver/pubspec.yaml, widget_driver_annotation/pubspec.yaml, widget_driver_generator/pubspec.yaml, widget_driver_test/pubspec.yaml
As per request https://github.com/bmw-tech/widget_driver/issues/174, updating `mocktail` dependency to the latest version.
=> [174]: Updating mocktail dependency to the version 1.0.4
